set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Video streaming module for FreeSWITCH.")
set(CPACK_PACKAGE_DESCRIPTION "This module allows video streaming from FreeSWITCH to WebSocket servers, enabling real-time video processing and forwarding.")

set(CPACK_PACKAGE_VENDOR "voxcom-us")

set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_SOURCE_DIR}/_packages")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Emmanuel S <emmanuel@voxcom.us>")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/voxcom-us/mod_video_stream")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)#ONE_PER_GROUP)
set(CPACK_DEB_COMPONENT_INSTALL YES)

set(CPACK_STRIP_FILES YES)

include(CPack)
